default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args:
          - --line-length=140
          - --fix
          - --select=ALL
          - --ignore=D100,D104,COM812,ISC001,T201,S101
          - --per-file-ignores=__init__.py:F401,tests/*:S101,PLR0913,PLR2004
      - id: ruff-format
        args: [--line-length=140]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports, --show-error-codes]
        additional_dependencies: [types-requests, types-PyYAML]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-r", ".", "-x", "tests,env,venv", "-ll"]

#  - repo: https://github.com/pyupio/safety
#    rev: 3.2.7
#    hooks:
#      - id: safety
#        args: ["--ignore", "70612"]
#
#  # Dead code detection (ruff F401, F841 help but vulture is more thorough)
#  - repo: https://github.com/jendrikseipp/vulture
#    rev: 'v2.11'
#    hooks:
#      - id: vulture
#        args: ["backend/src", "--min-confidence", "80"]
#
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: debug-statements

#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.5.0
#    hooks:
#      - id: detect-secrets
#        args: ['--baseline', '.secrets.baseline']
