# Fly.io configuration for Game Overview Python Backend
app = 'game-overview-backend'
primary_region = 'sjc'

[build]

[env]
  PORT = '8001'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = '/api/games/catalog'

[machine]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/static'
  url_prefix = '/static/'

[deploy]
  release_command = 'echo "No release command needed"'
