name = "backlogblitz-landing"
main = "worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "backlog_blitz_KV"
id = "4b75617f9fbe41f8a5057946addf5dcf"
preview_id = "509c31065b5b49daaf6ad765d186de46"

[env.staging]
name = "backlogblitz-landing-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.kv_namespaces]]
binding = "backlog_blitz_KV"
id = "4b75617f9fbe41f8a5057946addf5dcf"
preview_id = "509c31065b5b49daaf6ad765d186de46"

# Custom domains (configure these in Cloudflare dashboard)
# routes = [
#   { pattern = "backlogblitz.com", custom_domain = true },
#   { pattern = "www.backlogblitz.com", custom_domain = true }
# ]
