import {Injectable} from '@angular/core';
import {CollectionEntry} from '../domain/entities/CollectionEntry';

@Injectable({providedIn: 'root'})
export class ExportService {

  exportToMarkdown(games: CollectionEntry[]): void {
    const markdown = this.generateMarkdown(games);
    this.downloadFile(markdown, 'games.md', 'text/markdown');
  }

  generateMarkdown(games: CollectionEntry[]): string {
    const header = '> This file is automatically generated. Do not edit manually.\n\n';

    const backlogGames = games.filter(g => g.markedForLater);
    const regularGames = games.filter(g => !g.markedForLater);

    const sortedRegularGames = this.sortByRatingThenName(regularGames);
    const sortedBacklogGames = this.sortByRatingThenName(backlogGames);

    let content = header;

    content += '# Games\n\n';
    content += sortedRegularGames.map(game => this.formatGameLine(game)).join('\n');

    if (sortedBacklogGames.length > 0) {
      content += '\n\n# Backlog\n\n';
      content += sortedBacklogGames.map(game => this.formatGameLine(game)).join('\n');
    }

    content += '\n';

    return content;
  }

  private sortByRatingThenName(games: CollectionEntry[]): CollectionEntry[] {
    return [...games].sort((a, b) => {
      // Sort by rating descending (highest first)
      if (b.rating !== a.rating) {
        return b.rating - a.rating;
      }
      // Then by name ascending (alphabetically)
      return a.name.localeCompare(b.name);
    });
  }

  private formatGameLine(game: CollectionEntry): string {
    const checkbox = game.markedAsPlayed ? '[x]' : '[ ]';
    return `- ${checkbox} [[${game.name}]]`;
  }

  private downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], {type: mimeType});
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
