name = "nextbestgame"
main = "src/index.ts"
compatibility_date = "2024-07-01"

[assets]
directory = "./static"

[[d1_databases]]
binding = "DB"
database_name = "gameoverview-db"
database_id = "bd0ef27f-3efe-4f32-99ec-020a245d0223"

[[kv_namespaces]]
binding = "FEATURE_FLAGS"
id = "feature-flags-namespace"
preview_id = "feature-flags-preview"

[vars]
JWT_SECRET = "dev-secret-change-in-production"
ENVIRONMENT = "dev"
