name: Code Quality Metrics

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-climate:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qlty
      run: |
        curl https://qlty.sh | bash
        echo "$HOME/.qlty/bin" >> $GITHUB_PATH

    - name: Run Qlty Analysis
      run: |
        qlty init
        qlty check --format=github >> $GITHUB_STEP_SUMMARY

  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch full history for wily
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Run Radon Complexity Check
      run: |
        echo "## Cyclomatic Complexity Report" >> $GITHUB_STEP_SUMMARY
        uv run radon cc . --min=C --show-complexity --total-average >> $GITHUB_STEP_SUMMARY || true

    - name: Run Radon Maintainability Index
      run: |
        echo "## Maintainability Index Report" >> $GITHUB_STEP_SUMMARY
        uv run radon mi . --min=C --show >> $GITHUB_STEP_SUMMARY || true

    - name: Update Wily Database
      run: |
        uv run wily build --operators=cyclomatic,raw,maintainability

    - name: Generate Wily Report
      run: |
        echo "## Historical Metrics Comparison" >> $GITHUB_STEP_SUMMARY
        uv run wily report . --format=markdown >> $GITHUB_STEP_SUMMARY || true

    - name: Archive Wily Database
      uses: actions/upload-artifact@v4
      with:
        name: wily-database
        path: .wily/
